hoops-project/frontend

src/pages/Report/Report.style.ts
src/pages/Report/Report.tsx
src/routes/MainRouter.tsx

작업목적
- 관리자 페이지 중 신고 받는 영역 페이지 생성
작업 내용
- 관리자 페이지라서 page 폴더안에 따로 만들어서 제작을 하였습니다.
- react-route-dom을 이용을 해서 /report를 이용을 해서 제작을 하였습니다.
- 임의의 데이터를 이용을 해서 제작을 하였습니다.

feat:관리자 페이지 중 신고 페이지 생성

---

src/components/ReportItem/ReportItem.style.ts
src/components/ReportItem/ReportItem.tsx
src/pages/Report/Report.style.ts
src/pages/Report/Report.tsx

- 저번에 남긴 리뷰를 가지고 컴포넌트 화를 해서 수정을 하였습니다.
- /componet/reportItem 이런 작명을 가지고 수정을 하였습니다.

기존에 있는 report 컴포넌트를 한 번더 컴포넌트화 를 하였습니다.

---

src/hooks/useInfiniteScroll.ts

작업 목적
- 인피니티 스크롤을 편하게 구현하기 위한 커스텀 훅 생성
작업 내용
- react-query의 useInfiniteQuery와 intersectionobserver를 이용하여 인피니티 스크롤 로직을 커스텀 훅으로 만들었습니다. 
- DOM 요소가 뷰포트와 교차할 때마다 호출되는 handleObserver의 불필요한 생성을 막기 위해 useCallback을 이용하여 캐싱하였습니다.
- 기본적인 사용 방법은 다음과 같습니다.
```typescript
// useInfiniteQuery를 통한 데이터 패칭 로직
const { data, fetchNextPage, hasNextPage } = useInfiniteQuery({
queryKey: ['exampleKey'],
queryFn: async ({ pageParam }) => {
// 패칭 함수에서 한번에 가져올 데이터 갯수는 추후 자유롭게 설정
const response = await getExampleData(id, pageParam, 5); 
return response;
},
getNextPageParam: (lastPage, allPages) => {
const nextPage = allPages.length + 1;
const maxPage = Math.ceil((lastPage.count ?? 0) / 5); // 최대 페이지 계산
return nextPage <= maxPage ? nextPage : undefined; // 다음 페이지를 가져올지 말지 계산
},
initialPageParam: 1,
});
// …
```

hoops #32 인피니티 스크롤을 편하게 구현하기 위한 커스텀 훅 생성

---

src/components/SearchTab/SearchTab.style.ts
src/components/SearchTab/SearchTab.tsx
src/mock/data.ts
src/routes/MainRouter.tsx

- API 명세서 기준으로 User 정보를 작성해서 목데이터화 했습니다.
- 사용자 정보를 받아와서 친구 여부에 따라 다른 버튼이 나오도록 구현했습니다.
- 해당 유저 리스트 내에서 연동시 검색이 가능하게 구현될 예정입니다.

hoops #37 친구 검색 페이지 작성 및 User정보 목데이터 연동

---

src/components/common/MyLastGame/MyLastGame.style.ts
src/components/common/MyLastGame/MyLastGame.tsx
src/mock/data.ts
src/pages/MyLastGame/MyLastGame.tsx
src/routes/MainRouter.tsx

- 나의 지난 경기 페이지 작업 진행했습니다.
- 평가 가능 여부를 설정하여 버튼 색상 변경 적용, 기존 공통 컴포넌트인 BasicButton을 사용했습니다. 
- API 명세 기반으로 하는 목데이터 생성 후 해당 페이지에 들어가게끔 작업했습니다.
- 차후 세세한 부분은 수정해서 반영할 예정입니다.

Hoops #44 나의 지난 경기 리스트 페이지

---

src/components/common/RequestItem/RequestItem.tsx

작업 목적
- 오타로 인한 에러 수정
작업 내용
RequestItem 파일의 오타로 인한 레퍼런스 에러를 수정하였습니다.

hoops #51 오타로 인한 에러 수정

---

src/components/MainNav/MainNav.tsx
src/components/MatchData/MatchData.tsx

- ChartJS 타입 오류 수정하였습니다.
- 상단 Nav 지난 경기 라우팅 추가 완료하였습니다.

hoops#54 오류 수정 및 라우팅 추가 

---

src/api/QueryClient.ts
src/api/axiosInstance.ts
src/components/Calender/Calender.tsx
src/constants/queryKeys.ts
src/hooks/query/useGameList.ts
src/pages/Main/Main.tsx
src/store/calender.ts
vite.config.ts

작업 목적
- proxy 설정을 통한 CORS 문제 해결
작업 내용
- vite.config.ts 의 proxy 설정을 통한 CORS 문제 해결하였습니다.
간단하게 proxy 설정을 주석으로 설명드리자면
```typescript
const env = loadEnv(process.env.NODE_ENV as string, process.cwd(), '') // loadEnv 함수를 사용하여 .env 파일에서 환경 변수를 로드합니다.
// https://vitejs.dev/config/
export default defineConfig({
plugins: [react()],
server: {
proxy: { // 프록시 설정
'/api': { // '/api'로 시작하는 요청을 프록시합니다.
target: env.VITE_HOOPS_API_URL, // 프록시 대상 URL입니다. env.VITE_HOOPS_API_URL은 .env 파일에 정의된 환경 변수입니다.
changeOrigin: true, // 프록시 요청의 origin을 변경할지 여부를 지정합니다. true로 설정하면 프록시 요청의 origin이 target과 동일해집니다.
rewrite: (path) => path.replace(/^\/api/, ''), // 프록시 요청의 URL에서 '/api'를 제거합니다.
},
},
},
})
```
예들들어 http://localhost:5173/api/hello 라는 URL로 요청을 보낼 때 다음과 같은 과정이 진행됩니다.
1. 클라이언트의 요청 URL이 /api로 시작되므로 해당 프록시 설정이 적용된다. …

hoops #58 vite.config.ts 의 proxy 설정을 통한 CORS 문제 해결 및 연동 테스트

---

package-lock.json
package.json
src/api/axiosInstance.ts
src/components/SignInForm/SignInForm.tsx
src/constants/endPoint.ts
src/constants/queryKeys.ts
src/constants/validRules.ts
src/hooks/query/useLoginQuery.ts
src/hooks/useToast.ts
src/layout/DefaultLayout/DefaultLayout.tsx
src/main.tsx
src/store/store.ts
src/types/auth.ts

- 로그인 API 연동하였습니다. 
- 로그인 시 toast 알람을 띄워 깔끔하게 나올 수 있도록 구현했습니다!
```import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const useToast = () => {
const toastSuccess = (msg: string | undefined) => {
toast.success(msg);
};
const toastError = (msg: string) => {
toast.error(msg);
};
const toastInfo = (msg: string) => {
toast.info(msg);
};
const toastWarning = (msg: string) => {
toast.warning(msg);
};
return { toastSuccess, toastError, toastInfo, toastWarning };
};
export default useToast;
```
가장 기본적인 코드 구성으로 react-toastify를 구성하였습니다. 
이렇게 구현할 시 전역적으로 토스트 알람이 사용 가능하게
```export default function DefaultLayout() {
return (
<>
<Header />
<Outlet />
<Footer />
{/* 토스트 컨테이너 */}
<ToastContainer
position="top-right"
autoClose={2000}
hideProgressBar={false} …
```

hoops #57 로그인 연동 및 react-toastify 추가 

---

src/components/UserInfoEdit/UserInfoEdit.tsx
src/constants/endPoint.ts
src/constants/queryKeys.ts
src/helper/convertValueToName.ts
src/helper/findSelectIndex.ts
src/hooks/query/useUserInfoQuery.ts
src/hooks/useSelect.ts

작업 목적
- 마이페이지의 회원 정보 수정 기능 구현
작업 내용
- 마이페이지의 회원 정보를 수정 가능하게 서버 연동하였습니다.
- 비밀번호는 암호화 되어 초기에 넘어오기에 처음 페이지에 접속할때 표시하지 않고 빈 문자열로 설정하였습니다.
- 서버에 맞는 값으로 변경하여 넘겨주기 위하여 helper함수를 추가하였습니다.

hoops #69 마이페이지 프로필 수정 기능 완성

---

src/components/FindUserIdForm/FindUserId.style.ts
src/components/FindUserIdForm/FindUserId.tsx
src/hooks/query/useFindUserIdQuery.ts
src/pages/FindUserId/FindUserId.style.ts
src/pages/FindUserId/FindUserId.tsx
src/pages/SignIn/SignIn.tsx
src/routes/MainRouter.tsx

작업 목접
- 아이디 찾기 페이지 생성 및 서버 연동
작업내용 
- 이메일을 입력하면 아이디가 나오도록 구현하였습니다.
- 이메일은 기본적으로 유효성 검사를 거친 후 서버로 전송됩니다.
- 존재하지 않는 이메일을 입력한 경우 서버에서 내려온 메시지를 출력하도록 하였습니다.

hoops #79 유저 아이디 찾기 페이지 생성 및 서버 연동

---

src/api/axiosInstance.ts
src/hooks/query/useGetMyLastGameListQuery.ts

- 나의 지난 경기 리스트에서 리스트를 받아올 때 , 데이터가 추가적으로 받아와지는 것이 아닌 같은 페이지를 계속 반복해서 보여주는 오류가 발견되어 해결했습니다. 
- refreshToken을 갱신하는 과정에서 만료된 토큰을 계속 받아와 요청하는 오류가 생겨서 인스턴스를 수정하였습니다.

[fix] 추가적으로 발견된 오류 해결 

---

src/api/axiosInstance.ts

엑시오스 인스턴스 경로 수정하여 다시 머지 하겠습니다.

hotfix: 엑시오스 인스턴스 경로 수정

---

package-lock.json
src/api/axiosInstance.ts

hotfix: 배포문제 수정

---

src/api/axiosInstance.ts
src/constants/endPoint.ts
src/hooks/useWebSocket.ts

채팅은 /api 이 빠져서 요청해야 하기에 연결이 안되는 문제 해결 하였습니다.

hotfix: 채팅은 /api 이 빠져서 요청해야 하기에 연결이 안되는 문제 해결

---

.vercel.json
src/components/GameChat/GameChat.tsx
src/hooks/query/useExitGame.ts
src/pages/SignIn/SignIn.tsx

vercel.json 설정 파일 추가하여 다시 배포하겠습니다.

hotfix: vercel.json 설정 파일 추가

---

.vercel.json
src/api/axiosInstance.ts

hotfix: baseURL 변경

---

src/layout/DefaultLayout/DefaultLayout.tsx

알림 구독 URL이 배포된 서버 URL 로 바뀌지 않고 있었던 문제 수정하였습니다.

fix: 알림 구독 URL이 배포된 서버 URL 로 바뀌지 않고 있었던 문제 수정

---

src/layout/DefaultLayout/DefaultLayout.tsx

알림 구독 url "/api" 누락 수정 하여 다시 배포하겠습니다.

fix: 알림 구독 url "/api" 누락 수정

---

src/components/KakaoLogin/KakaoLogin.style.ts
src/components/KakaoLogin/KakaoLogin.tsx
src/pages/SignIn/SignIn.tsx

카카오 로그인 구동을 위해 쿼리를 일부 수정하였습니다.

fix: 카카오 로그인 리다이렉트를 위한 기능 구현

---

src/components/KakaoLogin/KakaoLogin.tsx
src/components/OAuthRedirect/OAuthRedirect.tsx
src/routes/MainRouter.tsx

- 로그인 요청 후 리다이렉트 되지 않는 이슈를 해결하였습니다.

fix: 로그인 오류 해결

---

src/components/Calender/Calender.tsx
src/components/OAuthRedirect/OAuthRedirect.tsx

소셜 로그인시 헤더 아이콘 변경이 안되는 문제 해결 및 메인 페이지 날짜 문제 수정 하여 다시 배포 하겠습니다

fix: 소셜 로그인시 헤더 아이콘 변경이 안되는 문제 해결 및 메인 페이지 날짜 문제 수정

---

src/components/OAuthRedirect/OAuthRedirect.tsx

fix: 로그인 상태 관리 스토어 삭제

---

src/components/GameUserList/GameUserList.tsx
src/components/SearchResult/SearchResult.tsx
src/hooks/query/useFriendActions.ts

친구 검색창에서 검색 후 해당 친구 삭제 /추가 기능 구현하였습니다.

hoops#115 친구 신청 및 삭제 기능 구현 

---

src/components/ChatList/ChatList.tsx
src/hooks/useWebSocket.ts

작업 목적
- 채팅기능에서 이전 채팅 목록 불러와 렌더링
작업 내용
- 이제 채팅방을 들어가면 이전 채팅 목록도 불러옵니다.

hoops #129 채팅 기능중 이전 채팅 내용 불러오기 기능 추가

---

src/layout/Header/Header.tsx

카카오 로그인시 헤더 아이콘이 바뀌지 않는 문제 수정 하고 다시 배포 하겠습니다.

fix: 카카오 로그인시 헤더 아이콘이 바뀌지 않는 문제 수정

---

src/components/OAuthRedirect/OAuthRedirect.tsx
src/layout/DefaultLayout/DefaultLayout.tsx
src/layout/Header/Header.tsx

카카오 로그인시 헤더 아이콘이 바뀌지 않는 문제 다시 수정

fix: 카카오 로그인시 헤더 아이콘이 바뀌지 않는 문제 다시 수정 

---

src/components/Notification/Notification.tsx
src/components/SearchInput/SearchInput.style.ts
src/components/SearchInput/SearchInput.tsx
src/hooks/query/useAcceptGameRequestQuery.ts
src/hooks/query/useGetFriendListQuery.ts
src/hooks/query/useParticipantGameQuery.ts
src/hooks/useWebSocket.ts
src/pages/Report/Report.tsx

경기 참여 및 경기 참여 요청 수락시 데이터가 업데이트가 안되는 문제 수정

hotfix: 경기 참여 및 경기 참여 요청 수락시 데이터가 업데이트가 안되는 문제 수정

---

src/hooks/query/useGetMyLastGameListQuery.ts

지난경기 불러올때 한번에 불러오는 size 수 변경하여 다시 배포하겠습니다.

fix: 지난경기 불러올때 한번에 불러오는 size 수 변경

---

src/components/FriendList/FriendList.tsx
src/components/GameUserList/GameUserList.tsx
src/components/ReportItem/ReportItem.tsx
src/components/common/MyFriend/MyFriend.tsx
src/constants/endPoint.ts
src/hooks/query/useReportQuery.ts
src/main.tsx
src/types/auth.ts

hotfix: 신고하기 엔드포인트 오류 수정

---

src/components/Calender/Calender.tsx
src/components/MainNav/MainNav.tsx
src/components/MatchItem/MatchItem.tsx
src/components/MatchPoint/MatchPoint.tsx
src/components/SignInForm/SignInForm.tsx
src/components/common/SelectBox/SelectBox.tsx
src/layout/Header/Header.tsx
src/pages/Detail/Detail.tsx
src/pages/SignUp/SignUp.tsx

작업목적
- light house의 결과를 기반으로 접근성 개선
작업 내용
- aria-label이 누락된 부분을 찾아 추가함으로써 웹 접근성 향상
- 누락된 이미지 alt 속성 추가
- 대비가 부족한 글자 및 버튼 색상 변경
- 기존 접근성 점수 86점에서 91점까지 5점 상승

hoops g#140 접근성 개선

---

src/main.tsx

refactor: msw주석처리

---

src/hooks/query/useLoginQuery.ts
src/hooks/useWebSocket.ts

작업내용
채팅시 채팅 참여 여부 표시 및 백엔드와의 응답값을 맞춤

refactor: 채팅시 채팅 참여 여부 표시

---

src/hooks/query/useJoinGameQuery.ts
src/hooks/query/useLoginQuery.ts
src/hooks/query/useSignUpQuery.ts

작업내용
회원가입 중복검사 버그 및 경기참여 에러처리 버그 수정

fix: 회원가입 중복검사 버그 및 경기참여 에러처리 버그 수정
